services:
  keunsori-server:
    image: keunsori/keunsori-server:keunsori
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_NAME: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
