services:
  backend:
    image: ${IMAGE_URL}
    #    network_mode: host
    ports:
      - "80:8080"
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  :db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/var/lib/mysql
    platform: linux/x86_64