spring:
  application:
    name: keun-sori-server
  profiles:
    group:
      local: "local,datasource"
      dev: "dev,datasource"
      prod: "prod,datasource"
    include:
      - redis
      - email

jwt:
  secret: "${JWT_SECRET}"